apiVersion: apps/v1
kind: Deployment
metadata:
  name: universal-api-gateway
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gateway
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
